# Generated by Django 4.2.9 on 2024-01-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0002_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='instruction',
            field=models.TextField(blank=True),
        ),
    ]
