# Generated by Django 4.2.9 on 2024-01-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0005_remove_component_product_remove_component_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='product_components', to='arweb.component'),
        ),
    ]
