# Generated by Django 4.2.9 on 2024-01-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0006_step_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='product_components', to='arweb.component'),
        ),
        migrations.AlterField(
            model_name='step',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='step_components', to='arweb.component'),
        ),
    ]
