# Generated by Django 4.2.9 on 2024-01-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0007_alter_product_components_alter_step_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='12a', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
