# Generated by Django 4.2.9 on 2024-01-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0008_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
