# Generated by Django 4.2.9 on 2024-01-30 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0009_step_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
