# Generated by Django 4.2.9 on 2024-02-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0010_rename_title_component_name_alter_step_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='component_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
