# Generated by Django 4.2.9 on 2024-02-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0012_component_created_at_component_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
