# Generated by Django 4.2.9 on 2024-02-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0013_component_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='pt_model',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
