# Generated by Django 4.2.9 on 2024-02-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0014_step_pt_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='pt_model',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
