# Generated by Django 4.2.9 on 2024-03-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0015_alter_step_pt_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='component_pictures/'),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_id',
            field=models.CharField(max_length=15),
        ),
    ]
