# Generated by Django 4.2.9 on 2024-03-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0017_alter_component_component_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='components',
        ),
    ]
