# Generated by Django 4.2.9 on 2024-03-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0018_remove_product_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='product_components', to='arweb.component'),
        ),
    ]
