# Generated by Django 4.2.9 on 2024-03-17 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0019_product_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='components',
        ),
    ]
