# Generated by Django 4.2.9 on 2024-03-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0020_remove_product_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='pt_model',
        ),
        migrations.AddField(
            model_name='step',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='step_hint/'),
        ),
    ]
