# Generated by Django 4.2.9 on 2024-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arweb', '0021_remove_step_pt_model_step_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='step_hint/'),
        ),
    ]
