# Generated by Django 5.0 on 2024-01-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emp_id',
            field=models.CharField(default=12, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
