# Generated by Django 5.0 on 2024-01-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='emp_id',
            field=models.CharField(max_length=20),
        ),
    ]
