# Generated by Django 4.2.9 on 2024-01-21 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_is_online_alter_account_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
