# Generated by Django 4.2.9 on 2024-01-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_account_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=False),
        ),
    ]
