# Generated by Django 4.2.9 on 2024-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_account_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
